### PR TITLE
User select

### PR DESCRIPTION
**Pull request by dashaluna**
**In progress**

Opened branch for convenience to see the difference.

To Fix:
- [x] It doesn't seem to search for 1/2/3 letters even though I know where are users. For example, it finds results for `dasha`, but not for `das`. Ref: https://github.com/humanmade/shortcake/pull/2/commits/55e502d6594ca208bfd8438ff32030065ac8cf74
- [x] Ajax pagination is on drugs - keeps posting the same results to reach min display number. Ref: https://github.com/humanmade/shortcake/pull/2/commits/71c0d26dec3ac5ee49e5a55ce91fdb31ff944b2c The `new WP_User_Query()` didn't setup `number` by default - the equivalent of `posts_per_page`.

@BronsonQuick @mattheu how can we update our fork to the latest upstream? So this PR only shows my changes without the `term_select` things?

### CODE REVIEW

**Comment by mattheu** [comment]
I think the select2 AJAX settings accepts a 'minimum length' search string - which you can disable if you want.

**Comment by dashaluna** [comment]
I've updated HM shortcake master to the latests main repo master, but this PR still shows the term code that's already in master. Not sure what to do to only show my changes? Do I need push a new branch? @BronsonQuick any ideas? :)

**Comment by BronsonQuick** [comment]
@dashaluna I'd revert the `ee40c59f0d76f0bf6b71f9c2c0f33c0c76bea033` commit. If that doesn't work then I'd suggest that you create a new branch from `master` then cherry-pick in your `00935df91eb727fcd881b31bcc65dc0ae9ffa69f` commit into that.

**Comment by dashaluna** [comment]
@mattheu what's the best approach now:
1. Do you want to review it here and re-iterate if needed here before pushing to main `wp-shortcake` repo?
2. Shall I open PR against the main `wp-shortcake` repo now and you'll check it there?

**Comment by dashaluna** [comment]
@mattheu thanks for fixing and adding missing bits! What shall we do now? Close this PR and open against the main repo?

**Comment by mattheu** [comment]
I'd probably merge into `humanmade/shortcake` and open a new PR against the upstream version

**Pull request merged**
